name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # run at the start of every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.2']
        cabal: ['3.0.0.0', '3.2.0.0']
        os: [ubuntu-18.04, ubuntu-20.04]
	include:
	  - pciutils-tag: v3.5.2
	    pciutils-flag: libpci-352
	  - pciutils-tag: v3.6.0
	    pciutils-flag: libpci-360
	  - pciutils-tag: v3.7.0
	    pciutils-flag: libpci-370
#        pciutils: ['v3.5.2', 'v3.6.0', 'v3.6.4', 'v3.7.0']
    name: ${{ matrix.os }} GHC ${{ matrix.ghc }} Cabal ${{ matrix.cabal }} pciutils ${{ matrix.pciutils-tag }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout pciutils
      uses: actions/checkout@v2
      with:
        repository: pciutils/pciutils
        ref: ${{ matrix.pciutils-tag }}
        path: pciutils

    - name: Install pciutils
      run: |
        make CFLAGS='-O2 -Wall -W -Wno-parentheses -Wstrict-prototypes -Wmissing-prototypes -fPIC'
        sudo make install-lib CFLAGS='-O2 -Wall -W -Wno-parentheses -Wstrict-prototypes -Wmissing-prototypes -fPIC'
      working-directory: pciutils

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks -f${{ matrix.pciutils-flag }}
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks -f${{ matrix.pciutils-flag }} all
    - name: Run tests
      run: cabal test all
